#!/bin/bash

echo "FINAL MODEL COMPARISON"
echo "====================="
echo ""
echo "Testing all available models on key test cases..."
echo ""

# Test cases
echo "Test Case 1: 3 days, 93 miles, \$1.42 (Expected: \$364.51)"
echo "  RandomForest (run.sh):              $(./run.sh 3 93 1.42 2>&1 | tail -1)"
echo "  Decision Tree:                      $(./run_decision_tree.sh 3 93 1.42)"
echo "  Ultra-optimized:                    $(./run_standalone.sh 3 93 1.42)"
echo "  Optimized Standalone:               $(./run_optimized_standalone.sh 3 93 1.42)"
echo ""

echo "Test Case 2: 4 days, 69 miles, \$2321.49 (Expected: \$322.00)"
echo "  RandomForest (run.sh):              $(./run.sh 4 69 2321.49 2>&1 | tail -1)"
echo "  Decision Tree:                      $(./run_decision_tree.sh 4 69 2321.49)"
echo "  Ultra-optimized:                    $(./run_standalone.sh 4 69 2321.49)"
echo "  Optimized Standalone:               $(./run_optimized_standalone.sh 4 69 2321.49)"
echo ""

echo "SUMMARY OF SCORES:"
echo "=================="
echo ""
echo "Models requiring external files:"
echo "  1. RandomForest (run.sh):           Score 5363.90 (MAE ~\$52.64) ⭐ BEST"
echo "     - Requires: predict.py, rf_model.pkl"
echo "     - Most accurate but needs external model files"
echo ""
echo "Self-contained models:"
echo "  2. Optimized Standalone:            Score ~11719 (MAE ~\$117.19) ⭐ BEST STANDALONE"
echo "     - Depth-9 decision tree with residual corrections"
echo "     - All logic embedded in script"
echo ""
echo "  3. Decision Tree (current):         Score ~13161 (MAE ~\$132)"
echo "     - Depth-4 tree with corrections"
echo "     - Self-contained"
echo ""
echo "  4. Ultra-optimized parametric:      Score ~17209 (MAE ~\$172)"
echo "     - Rule-based with optimized parameters"
echo "     - Self-contained"
echo ""
echo "RECOMMENDATION:"
echo "==============="
echo "- If external files are allowed: Use RandomForest (run.sh) - Score 5363.90"
echo "- If must be self-contained: Use Optimized Standalone - Score ~11719" 